version: '3'

silent: true

tasks:
  build:
    cmds:
      - go build -o ./bin/app main.go
  run:
    cmds:
      - task build && ./bin/app

  transpile:
    dir: ../
    cmds:
      - task run

  css:build:
    cmds:
      - tailwindcss -i ./src/input.css -o ./dist/static/src/main.css
  css:watch:
    cmds:
      - tailwindcss -i ./src/input.css -o ./dist/static/main.css --watch


  transpile:watch:
    dir: ../
    cmds:
      - task dev

  run:watch:
    cmds:
      - nodemon -e "go" -i "example/src" -q --signal SIGTERM --exec "task run"

  dev:
    cmds:
      - task --parallel transpile:watch run:watch css:watch
