version: '3'

silent: true

vars:
  src: example/src
  dist: example/dist


tasks:
  build:
    cmds:
      - go build -o ./bin/gohtmlx .
  run:
    vars:
      src: "{{.src}}"
      dist: "{{.dist}}"
    cmds:
      - task build && ./bin/gohtmlx --src={{.src}} --dist={{.dist}}
  dev:
    cmds:
      - nodemon -e "go,html" -i "example/dist" -q --signal SIGTERM --exec "task run"
